### ISSUE TITLE
Error: invalid order function for sorting

### ISSUE THREAD

**Issue by lourenci** [elihunter173/dirbuf.nvim#14]
When I try to open a directory with `sort_order` set up to order by directories first, the following error happens:
```
Error executing lua ...m/site/pack/packer/opt/dirbuf.nvim/lua/dirbuf/buffer.lua:107: invalid order function for sorting
```

My setup:
```lua
  use {
    "elihunter173/dirbuf.nvim",
    cmd = {"Dirbuf"},
    config = function()
      require("dirbuf").setup {
          sort_order = function(l, r)
              return l.ftype == "directory"
          end,
      }
    end
  }
```

Thanks for the plugin.

**Comment by elihunter173** [comment]
Hi @lourenci ! Writing a custom `sort_order` can be a bit difficult. It's supposed to be a comparison function suitable for Lua's `table.sort()`, so it needs to have some properties of normal comparison like `<` so for example `sort_order(left, right) == not sort_order(right, left)`, which this function fails if left and right are both directories. 

As of 73f467f655b851ea7c1afdffc556c87d9c5a177b, I added some common sort orders as strings, so update and try out 
```lua
require("dirbuf").setup { sort_order = "directories_first" }
```

Behind the scenes this becomes
```lua
require("dirbuf").setup {
    sort_order = function(left, right)
        if left.ftype ~= right.ftype then
            return left.ftype < right.ftype
        else
            return left.fname < right.fname
        end
    end,
}
```
