### ISSUE TITLE
Update open buffers if file or directory (or parent directories!) renamed 

### ISSUE THREAD

**Issue by jeetsukumaran** [elihunter173/dirbuf.nvim#18]
Would it be possible for dirbuf to check to see if a rename operation would impact any open buffers and update accordingly after the operation (i.e.,internally and automatically  `:bw!` the old path and `:edit` the new one)?

**Comment by elihunter173** [comment]
I like this idea a lot! I've made mistakes with buffers not automatically being renamed before. It's a bit weird when you're doing a copy + move (i.e. a -> b, c) but I'm fine picking one arbitrarily as the one to rename buffers to then.

[vim-eunch:s `:Move` command](https://github.com/tpope/vim-eunuch/blob/e2c9e01abd2734919e65dd6fe6c84ca2a9b65a7d/plugin/eunuch.vim#L82-L105) might have some prior art for this. I'm also looking to see if any other Lua/libuv file managers have this feature

**Comment by elihunter173** [comment]
This feature has been implemented! Copy + move operations are resolved arbitrarily like I mentioned. Thank you for the suggestion. This was way easier than I expected and the results feel quite nice.

**Comment by jeetsukumaran** [comment]
That's awesome! Thanks -- I know this will be very useful to many :)
