### ISSUE TITLE
More actions for opening entry in Dirbuf

### ISSUE THREAD

**Issue by RnYi** [elihunter173/dirbuf.nvim#19]
For example, I want to open a file in a new tab.

**Comment by elihunter173** [comment]
I've wanted to add something like this, so I guess this is my push to actually do it. Here's my thoughts.

Ideally, there would be another a new command `:DirbufEnter` which would do the same thing that `<Plug>(dirbuf_enter)` does currently but is compatible with `:tab {cmd}`, `:vertical {cmd}`, etc. This should handle your simple case of opening an entry in a new tab by creating something like
```vim
autocmd FileType dirbuf nnoremap <buffer> whatever <cmd>tab DirbufEnter<cr>
```

Then I would also provide a new function `require("dirbuf").get_cursor_path()` which returns the current path under the cursor, which should handle more complicated use cases where you want to do something other than just opening a file.

**Comment by elihunter173** [comment]
This has been implemented on `main`.

423b21f1e9b171c3df88395d787781736d742f37 implements a `require("dirbuf").get_cursor_path()` function exactly like I described in my earlier comment.

445ed8b0d35d132473a1d39481d10e8fbcd6ab4f adds a `cmd` parameter to `require("dirbuf").enter()`, which defaults to "edit". You can read `:help dirbuf.enter()` for more docs, but the gist is you can pass alternative edit commands (e.g. "tabedit" or "split") to open things in new tabs, splits, etc. So your use case of opening in a new tab should look something like this
```vim
autocmd FileType dirbuf nnoremap <buffer> whatever <cmd>lua require'dirbuf'.enter('tabedit')<cr>
```

Aside: @megalithic you should be able to switch back to mainline dirbuf.nvim if you want. Thanks for the implementation idea :)
