### ISSUE TITLE
[Question] How might we have DirBuf open to the PWD of the current buffer?

### ISSUE THREAD

**Issue by megalithic** [elihunter173/dirbuf.nvim#30]
I love dirbuf!

I was wondering if there was some way to have dirbuf "start" in the PWD of the current buffer/file? 

Thanks so much! This has scratched my itch for an easy to use, super useful "tree" plugin.

**Comment by megalithic** [comment]
Found it. thanks!

**Comment by elihunter173** [comment]
You can also call `:Dirbuf %` or use the `<Plug>(dirbuf_up)` mapping which also respects counts
