### ISSUE TITLE
Feature Request: Popd-like interface

### ISSUE THREAD

**Issue by Diegovsky** [elihunter173/dirbuf.nvim#35]
We currently have "-" mapped to (dirbuf_up), but it would be great to also have something like a directory history to go back to, just like a "back" button in a browser.

I instinctively use <C-i> and <C-o> to navigate jump lists, so it would be very nice to have something like it for dirbuf. I'm not talking about implementing it as a the jump list, just using it as an example.

**Comment by elihunter173** [comment]
This seems reasonable. Do you know of any examples of other file managers / plugins which do this?

**Comment by elihunter173** [comment]
This functionality exists now with commit 5a1880a33a2ca35cabaf0305cebfe8e0653f5e6c. You can use the `<Plug>(dirbuf_history_forward)` and `<Plug>(dirbuf_history_backward)` to navigate the history

**Comment by Diegovsky** [comment]
Noice! Thank you so much :D
