### ISSUE TITLE
Demo video in README is broken

### ISSUE THREAD

**Issue by andrewferrier** [elihunter173/dirbuf.nvim#47]
As per title. On this page (https://github.com/elihunter173/dirbuf.nvim), I just see 'No video with supported format...'.

**Comment by elihunter173** [comment]
What browser and what version are you running? It works for me on both Chromium and Firefox
```
$ chromium --version
Chromium 104.0.5112.101 Arch Linux
$ firefox --version
Mozilla Firefox 104.0
```

**Comment by andrewferrier** [comment]
Hmm, I can't recreate this now! Sorry. I'll close this.
