### ISSUE TITLE
'autochdir' results in empty directory buffer

### ISSUE THREAD

**Issue by vellankiindeevar** [elihunter173/dirbuf.nvim#48]

**Comment by elihunter173** [comment]
This was introduced by e0044552dfd865556e2ea5e603e4d56f705c5bba

**Comment by elihunter173** [comment]
Works when you `:edit` after opening a directory buffer

**Comment by vellankiindeevar** [comment]
ah thats just so vim way of doing not the neovim way .

**Comment by elihunter173** [comment]
Sorry I should be clear that the last comment was a note for myself. The commit was for if you want to revert to an older version that doesn't have this bug.

I've been busy personally so I don't know when I'll be able to fix this bug

**Comment by elihunter173** [comment]
@ggandor @vellankiindeevar Just fixed the issue! :grin:
