### ISSUE TITLE
Feature: Custom actions

### ISSUE THREAD

**Issue by sayanarijit** [elihunter173/dirbuf.nvim#51]
A simple API to get the hovered or selected paths (absolute) along with their IDs so that I can perform custom actions on them.

A simple API to bind the custom actions to key bindings when in the directory buffer.

**Comment by andrewferrier** [comment]
The first already exists: https://github.com/elihunter173/dirbuf.nvim/blob/ac7ad3c8e61630d15af1f6266441984f54f54fd2/doc/dirbuf.txt#L110

The second is straightforward - use `vim.keymap.set()` in `after/ftplugin/dirbuf.lua` with `buffer = true`. I don't think it needs a specific API. You can find an [example in my config](https://github.com/andrewferrier/dotfiles/blob/f11866c0a91c0ae3c4c166d07fa5fa8a5013fa6c/common/.config/nvim/after/ftplugin/dirbuf.lua#L7).

**Comment by sayanarijit** [comment]
Nice. Thanks 👍
